// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// hugeglassoscrEigen
List hugeglassoscrEigen(Eigen::MatrixXd S, Eigen::MatrixXd W, Eigen::MatrixXd T, int dd, double lambda, int df);
RcppExport SEXP _huge_hugeglassoscrEigen(SEXP SSEXP, SEXP WSEXP, SEXP TSEXP, SEXP ddSEXP, SEXP lambdaSEXP, SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type S(SSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type W(WSEXP);
    Rcpp::traits::input_parameter< Eigen::MatrixXd >::type T(TSEXP);
    Rcpp::traits::input_parameter< int >::type dd(ddSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(hugeglassoscrEigen(S, W, T, dd, lambda, df));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_huge_hugeglassoscrEigen", (DL_FUNC) &_huge_hugeglassoscrEigen, 6},
    {NULL, NULL, 0}
};

RcppExport void R_init_huge(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
