# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hugeglasso <- function(S, lambda, scr, verbose, cov_output) {
    .Call(`_huge_hugeglasso`, S, lambda, scr, verbose, cov_output)
}

RIC <- function(X, d, n, r, t) {
    .Call(`_huge_RIC`, X, d, n, r, t)
}

SFGen <- function(d0, d) {
    .Call(`_huge_SFGen`, d0, d)
}

SPMBgraph <- function(S, lambda, nlambda, d, x, col_cnz, row_idx) {
    .Call(`_huge_SPMBgraph`, S, lambda, nlambda, d, x, col_cnz, row_idx)
}

SPMBgraphlasso <- function(data, lambda, nlambda, d, x, col_cnz, row_idx) {
    .Call(`_huge_SPMBgraphlasso`, data, lambda, nlambda, d, x, col_cnz, row_idx)
}

SPMBgraphsqrt <- function(data, lambda, nlambda, d, x, col_cnz, row_idx) {
    .Call(`_huge_SPMBgraphsqrt`, data, lambda, nlambda, d, x, col_cnz, row_idx)
}

SPMBscr <- function(S, idx_scr, lambda, nlambda, d, nscr, x, col_cnz, row_idx) {
    .Call(`_huge_SPMBscr`, S, idx_scr, lambda, nlambda, d, nscr, x, col_cnz, row_idx)
}

